### PR TITLE
Added Logging and exmplary logging checkpoints

### LINKED ISSUE #52: Introducing Logging capabilities
**Is your feature request related to a problem? Please describe.**
The absence of logging capabilities in the current codebase makes it challenging to trace issues, understand the application's execution flow, and diagnose problems effectively. This lack of logging can hinder efficient debugging and monitoring, particularly in complex scenarios.

**Describe the solution you'd like**
The introduction of a comprehensive logging system across the codebase is recommended including different logging levels and customizeable output directory

**Describe alternatives you've considered**
Print statements might serve as temporary solutions; however, they are not feasible as the codebase grows.

**Additional context**
Implementing a structured logging system would enhance the application's maintainability, supportability, and overall reliability. Usng a logging framework would also improve diagnosis in container enviroment

### PR DESCRIPTION
**Pull request by hunnguye**
**What's in the PR**
Added basic logging capabilities. Resolves #52 

**How to test manually**

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by serwarde** [comment]
Thank you for the work, it's a useful issue! I'll take a look at it

**Comment by serwarde** [comment]
The implementation looks good, but could you expand it to the lead view too please?
And there is a conflict after the last merge on the main branch that needs to be solved too

**Comment by hunnguye** [comment]
Hey, 
I resolved the merge conflict and updated the approach to use a YAML file for logger configuration

Given the complexity of the project I believe it's rather a better approach, if logs are successively implemented as the development progresses. Realistically, I don't think I am able to get familiar with the codebase in an appropriate time frame.

**Review by serwarde — APPROVED** [review]
LGTM

**Pull request merged**
